Assignments/pig latin
bhs-intro-to-programming/AlexEraso pull request #3
Opened 2022-09-16 22:16 UTC by AlexEraso

2022-09-17 02:49 UTC, gigamonkey requested changes
This code is fine and correct. But why don't you go ahead and make the chances I suggested and then request another review. You can click the recycle icon next to `gigamonkey` up at the top right of this page to request another review. (I *think* that will make it easier for me to find quickly.)

![2022-09-16 at 7 49 PM](https://user-images.githubusercontent.com/250053/190837735-bff2209d-1c91-40d8-9293-d02a76e0d5a3.png)

2022-09-17 02:49 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +const pigLatin = (word) =>
This is pretty good. However when you have to do something as complicated (both in the number of characters it takes up in the program and in the work it's doing in the computer as `word.search(/[aeiou]/)` it can be good to do it just once and capture it in a variable and then use the variable in all the places it occurs:

```javascript
const pigLatin = (word) => {
  const i = word.search(/[aeiou]/);
  return word.substring(i) + word.substring(0, i) + 'ay';
};
```

This has a couple readability benefits. First off we only have to think about one thing to understand the first line. We figure out what `word.search(/[aeiou]/)` is doing (finding the index of the first vowel) and then see that we're saving that value. Then we can understand the next line without having to also figure out the first bit. Also it's easier to see that the `i` occurs in two places than to carefully check that it's the same complex expression in the same two places.

Note that we had to abandon the shorthand function syntax and introduce `{}`s around the function body and a `return` statement to return the value. But it's worth it.

2022-09-17 02:49 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +const advancedPigLatin = (word) =>
Thus function has the same opportunity as the other except it's even more valuable because the complex search expression occurs three times and they all could be replaced with a reference to a variable.

2022-09-20 03:31 UTC, gigamonkey requested changes
Really close.

2022-09-20 03:31 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  i === 0 ? word + 'way' :
This expression (starting on this line and continuing on the next) is the right expression. Unfortunately you don't do anything with the value and then on line 50 you return the original value of `word`. If you instead put the `return` in front of this expression and get rid of line 50, then the value computed here would be returned from the function.

2022-09-20 04:07 UTC, AlexEraso commented on assignments/pig-latin/code.js
> +  i === 0 ? word + 'way' :
@gigamonkey

2022-09-21 00:32 UTC, gigamonkey approved these changes
Looks good. Ship it!

2022-09-22 21:38 UTC, merged