Projects/pomodoro timer
bhs-intro-to-programming/AlexEraso pull request #37
Opened 2023-02-08 23:32 UTC by AlexEraso

I didn't get what the "p.querySelector('#counter').textContent = `${counter}`;" does

2023-02-09 04:17 UTC, gigamonkey requested changes
Perhaps your biggest problem is that you wiped out the original HTML I gave you and lost the `<script>` tag that connects your Javascript to your webpage. Then you can see error messages about your code, fix them, and get it working.

2023-02-09 04:17 UTC, gigamonkey commented on projects/pomodoro-timer/public/index.html
>  </head>
You lost your `script` tag:

Add this line back:

```javascript
<script src="/scripts/script.js" type="module"></script>
```

Then you can actually debug your code. But at the moment your code is never even loaded so you have no way of getting error messages about syntax errors or seeing what it does when it's in a state to run.

2023-02-10 03:08 UTC, AlexEraso commented
I fixed it

2023-02-10 03:08 UTC, merged

2023-02-10 17:21 UTC, gigamonkey reviewed
Getting close. However you're back to your bad old ways of merging your PR before I've reviewed it.

2023-02-10 17:26 UTC, gigamonkey commented
Oh, as a pointer to some code you can look at, the bell schedule app I wrote clearly has code to make a nice countdown string. You can find it here: https://github.com/gigamonkey/bells/blob/main/bells.js

I won't give you a pointer to the exact function because that would make it too easy but you should be able to find it in here and then adapt the technique I use for you own code.

2023-02-10 22:50 UTC, AlexEraso commented on projects/pomodoro-timer/public/scripts/script.js
> +function fiveminutetimer(){
Ok I didn't know that the code was directly from someone on overflow bc I joined a discord server that helps people with problems with their code and sorta explain it to them. So this person showed me code that is used to make a timer and explained to me now it works and stuff, but I didn't know that it was from that. And it's kinda weird to credit a random server admin on discord so since I, for the most part understand it, I sorta just put it in there. But since you're telling me it's from that, I'll credit it.